# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37afd8a7ab34bb83925d5fe22a8f06d5579d500ad1171883f8d96ffebdf2b4fa4ac4af8070e7bf8dde30ae8798654df4b8a3589bb0ef33f48596f0c4b6aac1d4

test:
  secret_key_base: 65f2c62907aafdb29bdd4c7ec6fd0f2db2afad49e5ed430f5fdc1ea4603e124b3270348e78ae9250de6ff68e296af225d6f92e0fd7b10f7c9b5a62483b5f5dfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
